document-[click_here](https://docs.google.com/document/d/1t0H64vkTHa_PqceXz-DHDZI2ad2QJpaHjNudoWxI3J0/edit#heading=h.oeqazslpllz9)

session-document-[click-here](https://docs.google.com/document/d/1gQjR0OaeopGFyyxAV6kKZiZf1kMNeiAfHx6hXtCaGv0/edit)

In [1]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

49
0.38100852793520457


In [3]:
#creating n-dimensional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))


[15 99 59]
[[93  0 52 91]
 [43 13 40 29]
 [88 97 54 60]]
[[[88 11]
  [46 71]
  [94 43]
  [99  8]]

 [[43  3]
  [17 80]
  [ 3  9]
  [66 39]]

 [[39  7]
  [30  7]
  [38 41]
  [11 12]]]


In [4]:
#creating n-dimensional array with random floating-point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.014850535598654457
[0.70197462 0.97996222 0.76709308]
[[0.08261501 0.01342651 0.15279566]
 [0.19266899 0.23864211 0.21674455]]


In [5]:
a = random.randint(100,size=(3,2)).ravel()
a

array([98, 96,  6, 48, 25, 39])

In [8]:
#single element will be selected
random.choice(a)

25

In [12]:
# for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 2, 3, 4],
       [5, 2, 1, 4],
       [2, 1, 2, 5],
       [1, 4, 2, 4]])

### Pandas:
1. Data manipuation,analysis and cleaning
2. Tabular,unlabelled

### Creating a DataFrame
1. using 2 dictionaries
2. simple dictionary --> DataFrame

In [18]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"First":dict1,"second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

First  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [19]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'f':9}
data = {"First":dict1,"second":dict2}
df = pd.DataFrame(data)
df

First  second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [20]:
#simple dictinary --> DataFrame
d1 = {"name":["preeti","mounika","sumathi"],"address":["hyd","adb","AP"]}
df1 = pd.DataFrame(d1)
df1

name address
0   preeti     hyd
1  mounika     adb
2  sumathi      AP

In [21]:
#simple dictinary --> DataFrame
d1 = {"name":["preeti","mounika","sumathi"],"address":["hyd","adb","AP","pune"]}
df1 = pd.DataFrame(d1)
df1

ValueError: arrays must all be same length

In [24]:
#using Series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,45.3,45.5,67.4,67.78,34.45,23.34,67.4,23])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"colum1":s1,"colum2":s2,"colum3":s3}
df3 = pd.DataFrame(data)
df3

colum1  colum2 colum3
0       1   12.23      a
1       2   23.34      b
2       3   45.30      c
3       4   45.50      d
4       5   67.40      e
5       6   67.78      f
6       7   34.45      g
7       8   23.34      h
8       9   67.40      i
9      10   23.00      j

### selecting the data from the DataFrame :
1. loc
2. iloc

In [32]:
type(df3)

pandas.core.frame.DataFrame

In [26]:
df3["colum2"]

0    12.23
1    23.34
2    45.30
3    45.50
4    67.40
5    67.78
6    34.45
7    23.34
8    67.40
9    23.00
Name: colum2, dtype: float64

In [27]:
df3[["colum2","colum3"]] #brackets

colum2 colum3
0   12.23      a
1   23.34      b
2   45.30      c
3   45.50      d
4   67.40      e
5   67.78      f
6   34.45      g
7   23.34      h
8   67.40      i
9   23.00      j

In [29]:
#single column
df3.loc[:,"colum1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: colum1, dtype: int64

In [30]:
df3.loc[:,["colum1","colum2"]]

colum1  colum2
0       1   12.23
1       2   23.34
2       3   45.30
3       4   45.50
4       5   67.40
5       6   67.78
6       7   34.45
7       8   23.34
8       9   67.40
9      10   23.00

In [33]:
#extracting multiple column values
df3.loc[0:5,["colum1","colum2"]]

colum1  colum2
0       1   12.23
1       2   23.34
2       3   45.30
3       4   45.50
4       5   67.40
5       6   67.78

In [34]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: colum1, dtype: int64

In [35]:
df3.iloc[0:4,0:1]

colum1
0       1
1       2
2       3
3       4

### Retrieving the information of DataFrame




In [36]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   colum1  10 non-null     int64  
 1   colum2  10 non-null     float64
 2   colum3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [37]:
df3.shape

(10, 3)

In [38]:
df3.columns

Index(['colum1', 'colum2', 'colum3'], dtype='object')

In [39]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [40]:
#first 5 rows --> default 5
df3.head()

colum1  colum2 colum3
0       1   12.23      a
1       2   23.34      b
2       3   45.30      c
3       4   45.50      d
4       5   67.40      e

In [41]:
#no. of rows mentioned-3
df3.head(3)

colum1  colum2 colum3
0       1   12.23      a
1       2   23.34      b
2       3   45.30      c

In [42]:
df3.tail()

colum1  colum2 colum3
5       6   67.78      f
6       7   34.45      g
7       8   23.34      h
8       9   67.40      i
9      10   23.00      j

In [43]:
df3.tail(2)

colum1  colum2 colum3
8       9    67.4      i
9      10    23.0      j

In [45]:
#randomly selects
df3.sample()

colum1  colum2 colum3
4       5    67.4      e

In [46]:
#randomly selects given no. of rows - 2
df3.sample(2)

colum1  colum2 colum3
3       4   45.50      d
6       7   34.45      g

In [47]:
df3.describe()

colum1     colum2
count  10.00000  10.000000
mean    5.50000  40.974000
std     3.02765  20.997852
min     1.00000  12.230000
25%     3.25000  23.340000
50%     5.50000  39.875000
75%     7.75000  61.925000
max    10.00000  67.780000

In [58]:
#renaming the column names
df3.rename(columns={"colum1":"first",
                    "colum2":"second",
                    "colum3":"third"})
df3

first  second third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   23.34     h
8      9   67.40     i
9     10   23.00     j

In [59]:
df3.rename(columns={"colum1":"first",
                    "colum2":"second",
                    "colum3":"third"},inplace=True)
